project_poll/app_poll/urls.py
from django.urls import path

from . import views, views_gen

app_name = "app_poll"
urlpatterns = [
    # path("", views.index, name="index"),
    # path("<int:question_id>/", views.detail, name="detail"),
    # path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("gen/", views_gen.IndexView.as_view(), name="index"),
    path("gen/<int:pk>/", views_gen.DetailView.as_view(), name="detail"),
    path("gen/<int:pk>/results/", views_gen.ResultView.as_view(), name="results"),
]

project_poll/project_poll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/", include("app_poll.urls")),
    path("moviefacts/", include("moviefacts.urls")),
    path("drf/", include("drf_quickstart.urls")),
    path("oauth/", include("social_django.urls")),
    path("", include("users.urls")),
]

project_poll/users/urls.py
from django.urls import path, include
from users import views


app_name = "users"
urlpatterns = [
    path("auth/dashboard/", views.dashboard, name="dashboard"),
    path("auth/accounts/login/", views.MyLoginView.as_view(), name="login"),
    path("auth/accounts/password_change/", views.MyPasswordChangeView.as_view(), name="password_change"),
    path("auth/accounts/password_change/done/", views.MyPasswordChangeDoneView.as_view(), name="password_change_done"),
    path("auth/accounts/password_reset/", views.MyPasswordResetView.as_view(), name="password_reset"),
    path("auth/accounts/password_reset/done/", views.MyPasswordChangeDoneView.as_view(), name="password_reset_done"),
    path("auth/accounts/reset/<uidb64>/<token>/", views.MyPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("auth/accounts/reset/done/", views.MyPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("auth/accounts/", include("django.contrib.auth.urls")),
    path("auth/register/", views.register, name="register" ),
]

project_poll/app_poll/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    chioce_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.chioce_text

project_poll/app_poll/views.py
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Question, Choice


def index(request: HttpRequest) -> HttpResponse:
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {
        "latest_question_list": latest_question_list
    }
    return render(request, "app_poll/index.html", context)


def detail(request: HttpRequest, question_id: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "app_poll/detail.html", {"question": question})


def results(request: HttpRequest, question_id: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "app_poll/results.html", {"question": question})


def vote(request: HttpRequest, question_id: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "app_poll/detail.html",
            {"question": question, "error_message": "You ditn`t select a choice."}
            )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("app_poll:results", args=(question.id,)))

project_poll/app_poll/templates/app_poll/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    {% block title %}
    <title>Polls</title>
    {% endblock title %}
</head>
<body>
    <section class="hero">
        <div class="hero-body">
            <p class="title">
                {% block heading %}
                <h2 class="title">Polls:</h2>
                <hr>
                {% endblock heading %}
            </p>
        </div>
    </section>

    
    {% block content %}
    {% endblock content %}
    
    {% block ending %}
    <p>Copyright 2023-{% now "Y" %}</p>
    {% endblock ending %}
    
</body>
</html>

project_poll/app_poll/templates/app_poll/detail.html
{% extends "app_poll/base.html" %}

{% block title %}
<title>{{question.question_text}}</title>
{% endblock title %}


{% block content %}
<form action="{% url 'app_poll:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h3>{{question.question_text }}</h3></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.chioce_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">

</form>

{% endblock content %}


<h2>{{ question.question_text }}</h2>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.chioce_text }}</li>
    {% endfor %}
</ul>

project_poll/app_poll/templates/app_poll/index.html
{% extends "app_poll/base.html" %}

{% block content %}
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <a href="{% url 'app_poll:detail' question.id %}">{{ question.question_text }}</a>
            </li>
        {% endfor %}
    </ul>

{% else %}
    <p>No polls available.</p>
{% endif %}
{% endblock content %}

project_poll/app_poll/templates/app_poll/results.html
{% extends "app_poll/base.html" %}

{% block title %}
<title>Results for: {{question.question_text}}</title>
{% endblock title %}

{% block content %}
<h2>{{ question.question_text }}</h2><br>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.chioce_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}</li>
    {% endfor %}
</ul>

<a href="{% url 'app_poll:index' %}">Vote again?</a>
{% endblock content %}