project_poll/project_poll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/", include("app_poll.urls")),
    path("moviefacts/", include("moviefacts.urls")),
    path("drf/", include("drf_quickstart.urls")),
    path("oauth/", include("social_django.urls")),
    path("", include("users.urls")),
]

project_poll/users/urls.py
from django.urls import path, include
from users import views


app_name = "users"
urlpatterns = [
    path("auth/dashboard/", views.dashboard, name="dashboard"),
    path("auth/accounts/login/", views.MyLoginView.as_view(), name="login"),
    path("auth/accounts/password_change/", views.MyPasswordChangeView.as_view(), name="password_change"),
    path("auth/accounts/password_change/done/", views.MyPasswordChangeDoneView.as_view(), name="password_change_done"),
    path("auth/accounts/password_reset/", views.MyPasswordResetView.as_view(), name="password_reset"),
    path("auth/accounts/password_reset/done/", views.MyPasswordChangeDoneView.as_view(), name="password_reset_done"),
    path("auth/accounts/reset/<uidb64>/<token>/", views.MyPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("auth/accounts/reset/done/", views.MyPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("auth/accounts/", include("django.contrib.auth.urls")),
    path("auth/register/", views.register, name="register" ),
]

project_poll/users/models.py
from django.db import models

# Create your models here.

project_poll/users/forms.py
from django.contrib.auth.forms import UserCreationForm


class CustomerUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email", )

project_poll/users/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.views import LoginView, PasswordChangeView, LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView
from django.urls import reverse_lazy
from django.http import HttpRequest, HttpResponse
from users.forms import CustomerUserCreationForm
from django.contrib.auth import login
# from django.contrib.auth.urls import urlpatterns


def dashboard(request):
    return render(request, "users/dashboard.html")


def register(request: HttpRequest):
    if request.method == "GET":
        return render(
            request,
            "users/register.html",
            {"form": CustomerUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomerUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse("users:dashboard"))


class MyLoginView(LoginView):
    template_name = "registration/login.html"


# class MyLogoutView(LogoutView):
#     template_name = "users/registration/login.html"


class MyPasswordChangeView(PasswordChangeView):
    template_name = "registration/my_password_change_form.html"
    success_url = reverse_lazy("users:password_change_done")


class MyPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = "registration/my_password_change_done.html"


class MyPasswordResetView(PasswordResetView):
    template_name = "registration/my_password_reset_form.html"
    success_url = reverse_lazy("users:password_reset_done")
    email_template_name = "registration/my_password_reset_email.html"


class MyPasswordResetDoneView(PasswordResetDoneView):
    template_name = "registration/my_password_reset_done.html"


class MyPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy("users:my_password_reset_complete")
    template_name = "registration/my_password_reset_confirm.html"


class MyPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "registration/my_password_reset_complete.html"

project_poll/users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    {% block title %}
    <title>AUTH</title>
    {% endblock title %}
</head>
<body>
    <h2>Welcome to my website!</h2>
    <hr>
    {% block content %}
    {% endblock content %}
</body>
</html>

project_poll/users/templates/users/dashboard.html
{% extends 'users/base.html' %}

{% block content %}
    <h4>Hello, {{ user.username|default:'guest' }}!</h4>
<div>
    {% if user.is_authenticated %}
        <a href="{% url 'users:logout' %}">Logout</a>
        <a href="{% url 'users:password_change' %}">Change password</a>
    {% else %}
        <a href="{% url 'users:login' %}">Login</a>
    {% endif %}
</div>



{% endblock content %}

project_poll/users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}
    <h4>Register</h4>
<div>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Register">
</form>
    <a href="{% url 'users:login' %}">Login</a>
</div>
{% endblock content %}